// packages/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'nos-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent { }

<div class="app">

  <nos-header></nos-header>

  <p class="intro">
    To get started, edit <code>src/app/app.component.html</code> and save to reload.
  </p>
  <p class="intro">Or test out the following demo functions!</p>
  <hr class="line-break" />

  <nos-actions></nos-actions>
</div>

// packages/react/src/views/App/index.jsx
import React from "react";
import PropTypes from "prop-types";

import Header from "../../components/Header";
import NOSActions from "../../components/NOSActions";

// const styles = {
//   "@import": "https://fonts.googleapis.com/css?family=Source+Sans+Pro",
//   "@global html, body": {
//     fontFamily: "Source Sans Pro",
//     margin: 0,
//     padding: 0,
//     backgroundColor: "#ffffff"
//   },
//   App: {
//     textAlign: "center"
//   },
//   intro: {
//     fontSize: "large"
//   },
//   lineBreak: {
//     width: "75%",
//     borderTop: "1px solid #333333",
//     margin: "32px auto"
//   }
// };

const App = ({ classes }) => (
  <div className={classes.App}>
    <Header title="A nOS dApp starter-kit!" />
    <p className={classes.intro}>
      To get started, edit <code>src/views/App/index.js</code> and save to reload.
    </p>
    <p className={classes.intro}>Or test out the following demo functions!</p>
    <hr className={classes.lineBreak} />
    <NOSActions />
  </div>
);

App.propTypes = {
  classes: PropTypes.object.isRequired
};

export default App;
