// packages/react/src/components/NOSActions/index.jsx
import React from "react";
import PropTypes from "prop-types";
import { injectNOS, nosProps } from "@nosplatform/api-functions/lib/react";

// const styles = {
//   button: {
//     margin: "16px",
//     fontSize: "14px"
//   }
// };

class NOSActions extends React.Component {
  handleAlert = async func => alert(await func);

  // handleGetAddress = async () => alert(await this.props.nos.getAddress());

  handleClaimGas = () => {
    const { nos } = this.props;
    nos
      .claimGas()
      .then(alert)
      .catch(alert);
  };

  render() {
    const { classes, nos } = this.props;

    const neo = "c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b";
    const gas = "602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7";
    const rpx = "ecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9";

    // Add your smart contract's scriptHash here
    const scriptHash = "";

    // The operation of your smart contract you want to (test)invoke
    const operation = "";

    // The necessary arguments for you (test)invoke
    const args = [];

    // The storagekey you want to query
    const key = "";

    // The asset, amount and receiver of your send function
    const receiver = "";
    const amount = "";
    const asset = gas;

    const invoke = { scriptHash, operation, args }; // and testInvoke
    const getStorage = { scriptHash, key };
    const send = { amount, asset, receiver };

    return (
      <React.Fragment>
        <button type="button" className={classes.button} onClick={() => this.handleAlert(nos.getAddress())}>
          Get Address
        </button>
        <button type="button" className={classes.button} onClick={() => this.handleAlert(nos.getBalance({ asset: neo }))}>
          Get NEO Balance
        </button>
        <button type="button" className={classes.button} onClick={() => this.handleAlert(nos.getBalance({ asset: gas }))}>
          Get GAS Balance
        </button>
        <button type="button" className={classes.button} onClick={() => this.handleAlert(nos.getBalance({ asset: rpx }))}>
          Get RPX Balance
        </button>

        <button type="button" className={classes.button} onClick={this.handleClaimGas}>
          Claim Gas
        </button>
        <button type="button" className={classes.button} onClick={() => this.handleAlert(nos.send(send))}>
          Send GAS to...
        </button>

        <button type="button" className={classes.button} onClick={() => this.handleAlert(nos.testInvoke(invoke))}>
          TestInvoke
        </button>
        {/*
          <button
            className={classes.button}
            onClick={() => this.handleAlert(nos.invoke(invoke))}
          >
            Invoke
          </button>
        */}
        <button type="button" className={classes.button} onClick={() => this.handleAlert(nos.getStorage(getStorage))}>
          GetStorage
        </button>
      </React.Fragment>
    );
  }
}

NOSActions.propTypes = {
  classes: PropTypes.objectOf(PropTypes.any).isRequired,
  nos: nosProps.isRequired
};

export default injectNOS(NOSActions);

// packages/angular/src/app/nos-actions/nos-actions.component.ts
import { Component } from '@angular/core';
import nos from '../../nos/nosStore';

@Component({
  selector: 'nos-actions',
  templateUrl: './nos-actions.component.html',
  styleUrls: ['./nos-actions.component.scss']
})
export class NosActionsComponent {
  nos = nos;

  neo = 'c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b';
  gas = '602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7';
  rpx = 'ecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9';

  // Add your smart contract's scriptHash here
  scriptHash = '';

  // The operation of your smart contract you want to (test)invoke
  operation = '';

  // The necessary arguments for you (test)invoke
  args = [];

  // The storagekey you want to query
  key = '';

  // The asset, amount and receiver of your send function
  receiver = '';
  amount = '';
  asset = this.gas;

  // and testInvoke
  invoke = {
    scriptHash: this.scriptHash,
    operation: this.operation,
    args: this.args
  };

  getStorage = {
    scriptHash: this.scriptHash,
    key: this.key
  };

  send = {
    amount: this.amount,
    asset: this.asset,
    receiver: this.receiver
  };

  handleAlert = async func => alert(await func);

  handleClaimGas = () =>
    this.nos
      .claimGas()
      .then(alert)
      .catch(alert)
}

<button class="button" (click)="handleAlert(nos.getAddress())">Get Address</button>

<button class="button" (click)="handleAlert(nos.getBalance({ asset: neo }))">Get NEO Balance</button>

<button class="button" (click)="handleAlert(nos.getBalance({ asset: gas }))">Get GAS Balance</button>

<button class="button" (click)="handleAlert(nos.getBalance({ asset: rpx }))">Get RPX Balance</button>

<button class="button" (click)="handleClaimGas()">Claim Gas</button>

<button class="button" (click)="handleAlert(nos.send(send))">Send GAS to...</button>

<button class="button" (click)="handleAlert(nos.testInvoke(invoke))">TestInvoke</button>

<button class="button" (click)="handleAlert(nos.invoke(invoke))">Invoke</button>

<button class="button" (click)="handleAlert(nos.getStorage(getStorage))">GetStorage</button>
